sudo: required
services:
- docker
env:
  global:
  - DOCKER_USERNAME=gjacquenot
  - secure: "NzXMnOFq9Y4qjf8Jh9KkCdP0PGBqC2nDVk7aqEPMZpALCgMTrbq6DVII2Q+wn2bRqlxpciHN//Tyx8UOaRN5UqIv4O8S8SiPhB73L9+uFEGAs1VdSU+goLJ1feoKerG0UXWuEOS8XQhAhRRbisn3eaMWxDZ21fjCUmffcM88uUqpFOqUpAmWr65dcSj+b4rBSQjSiHzAsG0gl2Dwku/nKdeilJEkB4Cf+eko+QbyP5ILxjKytGFxg6LU+T/sYHecXJDQFqNiyZg63BqM+6FYqIaZrX0sM24yWDgRNU45pyr5VgrDf3f+GYdItB6c4BuyY21iGEkssPOz4e5gWkVOew9wrYKhrq/g3tr01yWwwx4WC3b7y4JOO28gFB4GStS3tSixEQn3ukePMnrYZkUoArBeGYVoc8uIRiQWMPhNCOtHWv/MFLWOrm5L7ZLV50zB+DN2HQdSt+lcU+SKQKJPWUHQ6WIqy7ohM/ca4RtRyteZ8P2J0Kz/nJhrzw2deKeu03BfLATjZrjLL7uF1g2K4ErN7sKjVSoUbG7ZUFJUn7evIIHMahgGx+EwfSzj/4N6QHZgxWDfJ1fr3QnsthMV1ejC8jZOXnCMSalCn1hUTZ8kA6m8UDPq3q3CbbotN3DExLMJFHcjMRY0wU3rHZT3w9O5BnxgCWKkL4SSPWc2MBw="

before_install:
- echo "Before install"
before_script:
- docker pull gjacquenot/ssc_build_centos75 || true
script:
- docker build --pull --cache-from gjacquenot/ssc_build_centos75 --tag gjacquenot/ssc_build_centos75 .
after_script:
- docker images
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]];
  then
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  docker push gjacquenot/ssc_build_centos75 ;
  fi
notifications:
  email: true
